### ISSUE TITLE
SDK Error in azkcreator

### ISSUE THREAD

**Issue by epihel** [tooolbox/gozak#1]
I ran gozak a few times and it successfully converted a mobi file to azk.  But then it started failing with no error message.  When I ran azkcreator directly, I got this message:

Exception: Code: 2001 Message: Error while extracting resource from SDK: kindle:embed:0001 1

Googling this error returns nothing.  Any ideas?

**Comment by tooolbox** [comment]
(Ouch, I should probably make sure that it outputs any errors from azkcreator.  I suppose I hadn't had any previously.)

On that exception, I presume that you modified your file in some way?  If you were just repeatedly converting the same file, and it started erroring after X attempts, that would be very strange.

I'm not familiar with that error, but I do have a couple thoughts:

There is that list of files that needed to be extracted from Kindle Previewer, but that was just the list that I knew for sure that azkcreator needed.  You could try pulling more files out of Previewer and sticking them in the Amazon folder, perhaps?

I also have since gotten my Previewer working on my Mac, so if you want to throw your Mobi file up on Dropbox or something and give me a link, I can try converting with Previewer and see if there's a difference in behavior, or if I get the same error message.

**Comment by tooolbox** [comment]
@epihel Any luck with pulling more files in from Previewer?  Any thoughts on my previous questions?

**Comment by epihel** [comment]
I found that when the MOBI file contains a font file, you get the error "Error while extracting resource from SDK: kindle:embed:0001 1."  You get the error even if you copy all the files from the Kindle Previewer lib directory.  Since this is a book that's about to be published, I'd rather not upload it to DropBox, but if you include a font file in your MOBI test file, you should be able to reproduce the error.

**Comment by tooolbox** [comment]
@epihel (Sorry for the long delay.)

Interesting, I don't have that problem at all.  Here's what I'm doing:

1. Export ePub from InDesign CC
2. Unpack ePub
3. Run various processing scripts
4. De-obfuscate fonts
5. Repack ePub
6. Run through Kindlegen (v2.9)
7. Run Gozak

It comes out fine the other end.  I'm wondering, what format is your font?  Is it obfuscated perhaps?  Does Kindlegen say anything when you build your MOBI?  Are you using Kindlegen to build your MOBI, or something else?  Does the font display properly when you simply load your MOBI onto an eInk Kindle?

**Comment by epihel** [comment]
After more research, it looks like the problem was including an EOT version of the font, which, as far as I know, is only for IE and so shouldn't have been included in the first place.  I removed the EOT file and included only a TTF file.  It looks fine with only TTF on all versions in the Kindle Previewer, the actual Kindle PaperWhite device, and iBooks.  And Gozak runs just fine.  Thanks for the help in tracking down this problem, which, it turns out, had nothing to do with your program.

Looks like "kindle:embed:0001 1" means "including an EOT file."

**Comment by tooolbox** [comment]
@epihel, Glad to help!  And glad there's nothing in Gozak I need to fix.  Except, perhaps, pulling errors from azkcreator through to Gozak...  Separate issue, though.
