### ISSUE TITLE
Error running azkcreator

### ISSUE THREAD

**Issue by JayPanoz** [tooolbox/gozak#3]
Hi, 

Looks like I can't get gozak to work at all on Yosemite 10.10.5 as it always fails at running azkcreator (I got from the latest Kindle Previewer version a.k.a. v2.941). 

Since there is no output, the best I can provide with is: 

```
2015/09/19 18:40:15 Cleaning up...
2015/09/19 18:40:15 Gozak failed:
Error running azkcreator: (signal: trace/BPT trap) output:
```

Do you have any idea what may trigger this error? 

I've downloaded gozak, followed every step in the Read Me file, put it in `/usr/local/bin`. Didn't work.

I've re-downloaded gozak, made sure I followed every step, let in on desktop. Didn't work.

I've even tried to build it from scratch. Didn't work.

I've tried files from a previous version of Kindle Previewer, which works perfectly in Mavericks 10.9.5. Didn't work.

And since Amazon doesn't care at all about this KP issue, gozak is the only alternative right now.

**Comment by tooolbox** [comment]
Thanks for checking out gozak, @JayPanoz, and sorry you're having this issue.

I do still need to fix the code to pass through stderr from azkcreator itself; just haven't gotten to that yet.  If you have any experience with Go and want to submit a pull request for that, I would highly appreciate it.

In the meantime, so you don't have to wait for an update to gozak, the easiest way to discover any underlying error is to just run azkcreator directly.   The resultant folder will have an odd directory structure, and not be compressed, but you may get a clearer error message.  For example, in #1, the user found out that azkcreator was failing because of an EOT font he had in the MOBI.

To run azkcreator directly, you would use something like this command:
```bash
# (Writing this from memory--not on my dev machine currently)
cd gozak #wherever the gozak folder is
./amazon/azkcreator --source ~/Documents/book.mobi --target ~/Documents/temp
```

Let me know if this helps at all.  If you don't get an error from azkcreator directly...well then there's something entirely different going on.

**Comment by JayPanoz** [comment]
OK.

So running azkcreator directly, this is the error message I get, which I guess could help a little bit more: 

```
dyld: Library not loaded: /usr/X11/lib/libxcb.1.dylib
  Referenced from: /usr/local/bin/gozak/amazon/azkLibs/libX11.6.dylib
  Reason: image not found
Trace/BPT trap: 5
```

So the easy fix is…

```
sudo ln -s /opt/X11 /usr/X11
```

Since X11 is in the `opt` folder since OS X Yosemite…

**Comment by tooolbox** [comment]
Hey, well I'm glad that got sorted out.  I think it's odd that azkcreator needs X11, though, as it's a terminal program.  And, glad that KP is working for you again.

I'm going to close this, as I opened the other issue for passing through the stderr already.
